# Generated by Django 3.2.10 on 2021-12-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ROIControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi_x', models.IntegerField()),
                ('roi_y', models.IntegerField()),
                ('roi_w', models.IntegerField()),
                ('roi_h', models.IntegerField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_camera.camerasetting', verbose_name='카메라 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='TextROIControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_x', models.IntegerField()),
                ('text_y', models.IntegerField()),
                ('text_w', models.IntegerField()),
                ('text_h', models.IntegerField()),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_event.roicontrol', verbose_name='ROI 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='LineROIControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_x', models.IntegerField()),
                ('line_y', models.IntegerField()),
                ('line_w', models.IntegerField()),
                ('line_h', models.IntegerField()),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_event.roicontrol', verbose_name='ROI 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='IntervalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_interval', models.FloatField(choices=[('10sec', 10000.0), ('30sec', 30000.0), ('60sec', 60000.0)])),
                ('line_interval', models.FloatField(choices=[('10sec', 10000.0), ('30sec', 30000.0), ('60sec', 60000.0)])),
                ('text_interval', models.FloatField(choices=[('10sec', 10000.0), ('30sec', 30000.0), ('60sec', 60000.0)])),
                ('camera_interval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_camera.camerasetting', verbose_name='카메라 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='ColorROIControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_select', models.TextField(choices=[('빨강', 'red'), ('파랑', 'blue'), ('초록', 'green')])),
                ('color_x', models.IntegerField()),
                ('color_y', models.IntegerField()),
                ('color_w', models.IntegerField()),
                ('color_h', models.IntegerField()),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_event.roicontrol', verbose_name='ROI 아이디')),
            ],
        ),
    ]
