# Generated by Django 3.2.10 on 2021-12-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_event', '0002_lineparamcontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorroicontrol',
            name='color_select',
            field=models.TextField(choices=[('red', '빨강'), ('blue', '파랑'), ('green', '초록')]),
        ),
        migrations.AlterField(
            model_name='intervalcontrol',
            name='color_interval',
            field=models.FloatField(choices=[(10.0, '10sec'), (30.0, '30sec'), (60.0, '60sec')], default=10.0),
        ),
        migrations.AlterField(
            model_name='intervalcontrol',
            name='line_interval',
            field=models.FloatField(choices=[(10.0, '10sec'), (30.0, '30sec'), (60.0, '60sec')], default=10.0),
        ),
        migrations.AlterField(
            model_name='intervalcontrol',
            name='text_interval',
            field=models.FloatField(choices=[(10.0, '10sec'), (30.0, '30sec'), (60.0, '60sec')], default=10.0),
        ),
        migrations.AlterField(
            model_name='lineparamcontrol',
            name='line_gaussian_ksize',
            field=models.IntegerField(choices=[(3, '3'), (5, '5'), (7, '7')], default=3),
        ),
    ]
