# Generated by Django 3.2.10 on 2021-12-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSetting',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('camera_name', models.TextField(default='', max_length=255, verbose_name='카메라 이름')),
                ('camera_id', models.TextField(default='', max_length=255, verbose_name='카메라 아이디')),
                ('camera_pw', models.TextField(default='', max_length=255, verbose_name='카메라 비밀번호')),
                ('camera_ip', models.TextField(max_length=255, verbose_name='카메라 아이피')),
                ('camera_port', models.TextField(default='', max_length=255, verbose_name='카메라 포트')),
                ('camera_url', models.TextField(default='', max_length=255, verbose_name='RTSP URL')),
                ('camera_alive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CameraCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_capture', models.ImageField(null=True, upload_to='capture/', verbose_name='카메라 캡쳐')),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_camera.camerasetting', verbose_name='카메라 아이디')),
            ],
        ),
    ]
