# Generated by Django 3.2.10 on 2021-12-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasetting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
