# Generated by Django 3.2.10 on 2021-12-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_camera.camerasetting', verbose_name='카메라 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='LineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_camera.camerasetting', verbose_name='카메라 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='ColorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('green', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_camera.camerasetting', verbose_name='카메라 아이디')),
            ],
        ),
    ]
